### ISSUE TITLE
Contact process

### ISSUE THREAD

**Issue by NHO123** [en00x/Simple-Ticket-System-WordPress#3]
Hello,

Can we obtain the following processes using your helpdesk.

For logged in users users:
User only add the text he want to write and subject field ( no mail address field )

For guests:
They see a contactform containing:
– mail address field where they put their mail address.
– Subject field
– text field where they put their message

When they press "send" on the contact form with the above the form is sent and the user receives a link where they confirm their mail address and is then converted to a user ( this e-mail verification method has be WP core since 4.3 ) Also the ticket is opened.
Username for the username is generated based on their mail address ( alias )

Also the user should not be logged directly in when sending contact form.

Can this be obtained with you plugin ?

Best regards,

**Comment by timdahlmanns** [comment]
Hi,
when i understand you correct, the ticket submition at the moment is as you mentioned. 
It is possible to implement but not the usual way, that the one who requests help gets an account to handle these requests 😄 so i won't implement that, because it's a to specific feature
