### ISSUE TITLE
Fatal error: Cannot redeclare js_include_function()

### ISSUE THREAD

**Issue by KITGA** [en00x/Simple-Ticket-System-WordPress#4]
Ich habe ein Problem. Ich habe Ihr Plugin auf ein Testsystem installiert und ausgiebig getestet. Es ist wirklich toll und habe entschieden es auf meinen Livesystem zu nutzen. Leider bekomme ich jetzt beim öffnen
der Seite Fehlermeldungen

auf der Seite mit [ts_form] kommt die Meldung:

Fatal error: Cannot redeclare js_include_function() (previously declared in /homepages/22/**********/htdocs/***/wp-content/plugins/simple-support-ticket-system/simple-support-ticket-system.php:83) in /homepages/22/*********/htdocs/***/wp-content/plugins/simple-support-ticket-system/simple-support-ticket-system.php on line 82

auf der Seite mit [ts_tickets] kommt die Meldung:

Fatal error: Cannot redeclare js_include_function() (previously declared in /homepages/22/*********/htdocs/***/wp-content/plugins/simple-support-ticket-system/simple-support-ticket-system.php:97) in /homepages/22/********/htdocs/***/wp-content/plugins/simple-support-ticket-system/simple-support-ticket-system.php on line 96

Woran kann das liegen.

**Comment by timdahlmanns** [comment]
Das liegt mit großer Wahrscheinlichkeit daran, dass ein weiteres Plugin eine Funktion mit gleichem Namen deklariert. Am besten kurz alle anderen Plugins deaktivieren und dann bitte rückmelden, ob es den Fehler behebt.

**Comment by KITGA** [comment]
vielen Dank für die schnelle Rückmeldung. Ich habe alle Plugins deaktiviert. Leider bleibt die Fehlermeldung. Woran könnte es noch liegen?

**Comment by timdahlmanns** [comment]
Welche WordPress Versionen waren es jeweils in der Testumgebung und welche bei der live Seite?

**Comment by KITGA** [comment]
4.8 auf beiden Systemen. Auf dem einen funktioniert es und auf dem anderen nicht. Wo es nicht geht ist mit SSL Zertifikat. Kann das daran liegen?

**Comment by timdahlmanns** [comment]
Mh okay, das sollte damit eigentlich nichts zu tun haben. Ich habe allerdings die Kompatibilität mit 4.8 noch nicht getestet, aber das Problem ist eigentlich nichts wildes. Es wird lediglich an irgendeiner anderen Stelle im code schon eine Funktion mit selbem Namen deklariert. Dementsprechend sollte eine Umbenennung den Fehler beheben. Ich schaue mal, ob ich heute oder morgen Zeit dafür finde.

**Comment by KITGA** [comment]
Das wäre perfekt. Ich finde das Plugin echt toll. Wäre schade wenn es nicht läuft. Falls Fragen sind einfach kurz melden.

**Comment by KITGA** [comment]
ich konnte den Fehler beheben. In der header.php lag der Fehler. Mal noch eine andere Frage. Kann man das Plugin so einstellen das der hinterlegte Techniker direkt nach der Ticketerstellung eine E-Mail bekommt und somit weiß das ein neues Ticket eingegangen ist?   Ausserdem sind bei den ausgehenden Mails  die Umlaute falsch. Sieht in etwa so aus. Ã¼bernommen. Gibt es da einen Trick?
Vielen Dank für Deine Mühe

**Comment by KITGA** [comment]
Desweiteren werden die E-Mail über cgi-mailer@kundenserver.de versendet. Kann man das ändern?

**Comment by timdahlmanns** [comment]
Okay sehr gut.
Mit der E-Mail bei Ticketerstellung ist nicht implementiert, weil dann an alle, unter Umständen viele Techniker, eine Benachrichtigung raus geht.

Mit den Umlauten bei den Mails ist dann wohl ne falsche Formatierung der Mail im Code.

Die Sender Mailadresse ist die, welche in der php.ini konfiguriert ist. Am einfachsten wäre es dort die gewünschte Mailadresse anzugeben.

Machbar ist das beschriebene auf jeden Fall, aber momentan fehlt mir erstens die Zeit für "größere" Updates und zweitens hält sich die Nutzung sowie Feedback zum Plugin in Grenzen.
Für die Umlaute in den Mails finde ich aber vielleicht noch Zeit, um mal drüber zu schauen.

**Comment by KITGA** [comment]
Vielen Dank für die Infos. Mit der php.ini hab ich mir mal angeschaut. Stehe aber völlig auf den Schlauch.
Mein Server ist bei 1und1. Ich finde weder die Datei noch ist mir richtig klar was ich dort hineinschreiben soll wenn ich sie finden sollte bzw. anlege.

**Comment by KITGA** [comment]
alles geklappt. Schönes Ticketsystem. Hoffe das ihr es weiterentwickelt.
